<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="PN Cambodia Alumni Association">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="<?php echo $title . ' - ' . SITE_TITLE; ?>">
<meta name="twitter:description" content="Candidates for PNC Alumni Association Board Member Election for 2017 – 2018 mandate. #PNCAAElection #PNCAlumni #9April2017">
<meta name="twitter:image:src" content="<?php echo site_url(IMG_PATH . 'all-candidates-2017.jpg'); ?>">
<meta name="twitter:url" content="<?php echo base_url(); ?>">
<meta property="og:type" content="website">
<meta property="og:title" content="<?php echo $title . ' - ' . SITE_TITLE; ?>">
<meta property="og:description" content="Candidates for PNC Alumni Association Board Member Election for 2017 – 2018 mandate: Mr. Sophanith Chhom, Ms. Birosa Sareth, Ms. Rotha Rorng, Mr. Vannakpanha Mao, Mr. Vuthy Im, Ms. Chanthy Loem, Ms. Luot Kimheng, Ms. Makara Prom, Mr. Rith Nhel, Ms. Phatsa Sorn">
<meta property="og:image" content="<?php echo site_url(IMG_PATH . 'all-candidates-2017.jpg'); ?>">
<meta property="og:url" content="<?php echo base_url(); ?>">
<meta property="og:image:width" content="1024">
<meta property="og:image:height" content="1235">
<link rel="canonical" href="<?php echo base_url(); ?>">
<?php
echo link_tag('favicon.ico', 'shortcut icon', '');
echo link_tag(CSS_PATH . 'app.min.css');
?>
<title><?php echo $title . ' - ' . SITE_TITLE; ?></title>