<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<?php $this->load->view('partials/include-inside-head-tag.phtml'); ?>
</head>
<body>
	<?php $this->load->view('partials/header.phtml'); ?>
	<main class="container-fluid">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h1 class="panel-title"><?php echo $title; ?></h1>
			</div>
			<div class="panel-body">
				<?php
					$dir = $this->uri->segment(1);
					$file = $this->uri->segment(2);
					if (!empty($dir) && !empty($file)) {
						$this->load->view($dir . '/' . $file . '.phtml');
					} elseif (!empty($dir) && empty($file)) {
						$this->load->view($dir . '/index.phtml');
					} else {
						$this->load->view('election/index.phtml');
					}
				?>
			</div>
			<div class="panel-footer">
				<small>Copy &copy; by PN Cambodia Alumni Association - 2017. All right reserved!</small>
			</div>
		</div>
	</main>
	<script src="<?php echo site_url(JS_PATH . 'library.min.js'); ?>" defer></script>
	<script src="<?php echo site_url(JS_PATH . 'amcharts/amcharts.js'); ?>" defer></script>
	<script src="<?php echo site_url(JS_PATH . 'amcharts/serial.js'); ?>" defer></script>
	<script src="<?php echo site_url(JS_PATH . 'amcharts/themes/light.js'); ?>" defer></script>
	<script src="<?php echo site_url(JS_PATH . 'amcharts/tools/showValueLabels/showValueLabels.min.js'); ?>" defer></script>
	<script src="<?php echo site_url(JS_PATH . 'app.min.js'); ?>" defer></script>
</body>
</html>